# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 649)
        MainWindow.setMaximumSize(QtCore.QSize(987, 649))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/fondo/logo24x24-65.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_login_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_login_frame.setMinimumSize(QtCore.QSize(463, 359))
        self.main_login_frame.setSizeIncrement(QtCore.QSize(0, 759))
        self.main_login_frame.setStyleSheet("QFrame{\n"
"border-image: url(:/fondo/imagenfondo4-59.jpg);\n"
"}")
        self.main_login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_login_frame.setObjectName("main_login_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_login_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_frame = QtWidgets.QFrame(self.main_login_frame)
        self.login_frame.setMaximumSize(QtCore.QSize(381, 292))
        self.login_frame.setSizeIncrement(QtCore.QSize(500, 450))
        self.login_frame.setStyleSheet("background-color: rgba(0, 7, 66,200);\n"
"border-radius: 45px;\n"
"border-image: none\n"
"")
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.titulo_login_lbl = QtWidgets.QLabel(self.login_frame)
        self.titulo_login_lbl.setGeometry(QtCore.QRect(50, 47, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Cairo Black")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_login_lbl.setFont(font)
        self.titulo_login_lbl.setStyleSheet("color: #fff;\n"
"font-weight: bold;")
        self.titulo_login_lbl.setObjectName("titulo_login_lbl")
        self.subt_login_lbl = QtWidgets.QLabel(self.login_frame)
        self.subt_login_lbl.setGeometry(QtCore.QRect(50, 80, 155, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(25)
        self.subt_login_lbl.setFont(font)
        self.subt_login_lbl.setStyleSheet("font: 20px;\n"
"color: #fff;\n"
"font-weight: 200;\n"
"")
        self.subt_login_lbl.setObjectName("subt_login_lbl")
        self.user_login_input = QtWidgets.QLineEdit(self.login_frame)
        self.user_login_input.setGeometry(QtCore.QRect(50, 140, 281, 25))
        font = QtGui.QFont()
        font.setFamily("Cairo SemiBold")
        self.user_login_input.setFont(font)
        self.user_login_input.setStyleSheet("QLineEdit{\n"
"background: #fff;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"color: #000742;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 1px solid rgb(75, 75, 75);\n"
"}")
        self.user_login_input.setText("")
        self.user_login_input.setObjectName("user_login_input")
        self.pass_login_input = QtWidgets.QLineEdit(self.login_frame)
        self.pass_login_input.setGeometry(QtCore.QRect(50, 180, 281, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pass_login_input.setFont(font)
        self.pass_login_input.setStyleSheet("QLineEdit{\n"
"background: #fff;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"color: #000742;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 1px solid rgb(75, 75, 75);\n"
"}")
        self.pass_login_input.setText("")
        self.pass_login_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_login_input.setObjectName("pass_login_input")
        self.login_btn = QtWidgets.QPushButton(self.login_frame)
        self.login_btn.setGeometry(QtCore.QRect(50, 230, 91, 24))
        font = QtGui.QFont()
        font.setFamily("Cairo SemiBold")
        font.setPointSize(9)
        self.login_btn.setFont(font)
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.login_btn.setStyleSheet("QPushButton{\n"
"background-color: #055ffc;\n"
"color:#fff;\n"
"border-radius: 5px;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}\n"
"\n"
"QPushButton#login_btn:pressed{\n"
"padding-top: 3px;\n"
"padding-left: 3px;\n"
"}\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout.addWidget(self.login_frame)
        self.verticalLayout.addWidget(self.main_login_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bullsoft"))
        self.titulo_login_lbl.setText(_translate("MainWindow", "BIENVENIDO"))
        self.subt_login_lbl.setText(_translate("MainWindow", "Ingresa tus datos"))
        self.user_login_input.setPlaceholderText(_translate("MainWindow", "DNI Empleado"))
        self.pass_login_input.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.login_btn.setText(_translate("MainWindow", "Ingresar  "))
from  Interfaces.login.Img import img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
