# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_login_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_login_frame.setMinimumSize(QtCore.QSize(463, 359))
        self.main_login_frame.setSizeIncrement(QtCore.QSize(0, 759))
        self.main_login_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.00609095, y1:0, x2:0.966636, y2:0.955, stop:0 rgba(18, 21, 26, 255), stop:0.477273 rgba(26, 30, 35, 255), stop:1 rgba(18, 21, 26, 255));")
        self.main_login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_login_frame.setObjectName("main_login_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_login_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_frame = QtWidgets.QFrame(self.main_login_frame)
        self.login_frame.setMaximumSize(QtCore.QSize(381, 301))
        self.login_frame.setSizeIncrement(QtCore.QSize(500, 450))
        self.login_frame.setStyleSheet("background-color: #12151a;\n"
"border-radius: 45px\n"
"")
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.titulo_login_lbl = QtWidgets.QLabel(self.login_frame)
        self.titulo_login_lbl.setGeometry(QtCore.QRect(60, 20, 251, 81))
        self.titulo_login_lbl.setStyleSheet("font: 35px bold ,Roboto;\n"
"color: #fff;\n"
"font-weight: bold;")
        self.titulo_login_lbl.setObjectName("titulo_login_lbl")
        self.subt_login_lbl = QtWidgets.QLabel(self.login_frame)
        self.subt_login_lbl.setGeometry(QtCore.QRect(60, 90, 155, 24))
        self.subt_login_lbl.setStyleSheet("font: 20px;\n"
"color: #fff;\n"
"font-family: Roboto;\n"
"font-weight: 200;\n"
"")
        self.subt_login_lbl.setObjectName("subt_login_lbl")
        self.user_login_input = QtWidgets.QLineEdit(self.login_frame)
        self.user_login_input.setGeometry(QtCore.QRect(50, 150, 281, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.user_login_input.setFont(font)
        self.user_login_input.setStyleSheet("QLineEdit{\n"
"background: #23262b;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"color: #b3b3b3;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 1px solid rgb(75, 75, 75);\n"
"}")
        self.user_login_input.setText("")
        self.user_login_input.setObjectName("user_login_input")
        self.pass_login_input = QtWidgets.QLineEdit(self.login_frame)
        self.pass_login_input.setGeometry(QtCore.QRect(50, 190, 281, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pass_login_input.setFont(font)
        self.pass_login_input.setStyleSheet("QLineEdit{\n"
"background: #23262b;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"color: #b3b3b3;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 1px solid rgb(75, 75, 75);\n"
"}")
        self.pass_login_input.setText("")
        self.pass_login_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_login_input.setObjectName("pass_login_input")
        self.login_btn = QtWidgets.QPushButton(self.login_frame)
        self.login_btn.setGeometry(QtCore.QRect(50, 240, 91, 24))
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.login_btn.setStyleSheet("QPushButton#login_btn{\n"
"background-color: #1173ff;\n"
"color:#fff;\n"
"font-size:12px;\n"
"font-family: Roboto;\n"
"font-weight: bold;\n"
"border-radius: 5px;\n"
"padding-bottom: 1px\n"
"}\n"
"QPushButton#login_btn:hover{\n"
"background-color: #45a9f0;\n"
"}\n"
"\n"
"QPushButton#login_btn:pressed{\n"
"padding-top: 3px;\n"
"padding-left: 3px;\n"
"}\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout.addWidget(self.login_frame)
        self.verticalLayout.addWidget(self.main_login_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo_login_lbl.setText(_translate("MainWindow", "BIENVENIDO"))
        self.subt_login_lbl.setText(_translate("MainWindow", "Ingresa tus datos"))
        self.user_login_input.setPlaceholderText(_translate("MainWindow", "Código Empleado"))
        self.pass_login_input.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.login_btn.setText(_translate("MainWindow", "Ingresar  →"))
from Interfaces.loading.Img import  img
  
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
