# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bm_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 209))
        self.frame.setStyleSheet("background: #f5f5f5;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(230, 20, 221, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/aa.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background: #f5f5f5;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.modificarprod_btn = QtWidgets.QPushButton(self.frame_2)
        self.modificarprod_btn.setGeometry(QtCore.QRect(150, 340, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.modificarprod_btn.setFont(font)
        self.modificarprod_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modificarprod_btn.setStyleSheet("QPushButton{\n"
"background-color: #055ffc;\n"
"color:#fff;\n"
"border-radius: 5px;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.modificarprod_btn.setObjectName("modificarprod_btn")
        self.eliminarprod_btn = QtWidgets.QPushButton(self.frame_2)
        self.eliminarprod_btn.setGeometry(QtCore.QRect(410, 340, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.eliminarprod_btn.setFont(font)
        self.eliminarprod_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eliminarprod_btn.setStyleSheet("QPushButton{\n"
"background-color: #055ffc;\n"
"color:#fff;\n"
"border-radius: 5px;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.eliminarprod_btn.setObjectName("eliminarprod_btn")
        self.label_rep_mail = QtWidgets.QLabel(self.frame_2)
        self.label_rep_mail.setGeometry(QtCore.QRect(250, 160, 90, 27))
        self.label_rep_mail.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_rep_mail.setFont(font)
        self.label_rep_mail.setStyleSheet("font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_rep_mail.setObjectName("label_rep_mail")
        self.apellido_input = QtWidgets.QLineEdit(self.frame_2)
        self.apellido_input.setGeometry(QtCore.QRect(60, 190, 170, 28))
        self.apellido_input.setMinimumSize(QtCore.QSize(0, 0))
        self.apellido_input.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.apellido_input.setFont(font)
        self.apellido_input.setStyleSheet("QLineEdit{\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"\n"
"}")
        self.apellido_input.setPlaceholderText("")
        self.apellido_input.setObjectName("apellido_input")
        self.nombre_input_2 = QtWidgets.QLineEdit(self.frame_2)
        self.nombre_input_2.setGeometry(QtCore.QRect(60, 130, 170, 28))
        self.nombre_input_2.setMinimumSize(QtCore.QSize(0, 0))
        self.nombre_input_2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.nombre_input_2.setFont(font)
        self.nombre_input_2.setStyleSheet("QLineEdit{\n"
"background-color: #fff;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"border: 1px solid #b8b9bd;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"}\n"
"")
        self.nombre_input_2.setText("")
        self.nombre_input_2.setPlaceholderText("")
        self.nombre_input_2.setObjectName("nombre_input_2")
        self.tipo_cb = QtWidgets.QComboBox(self.frame_2)
        self.tipo_cb.setGeometry(QtCore.QRect(430, 70, 171, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tipo_cb.sizePolicy().hasHeightForWidth())
        self.tipo_cb.setSizePolicy(sizePolicy)
        self.tipo_cb.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tipo_cb.setFont(font)
        self.tipo_cb.setStyleSheet("\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"font-size:13px;\n"
"margin-left: 10px;\n"
"")
        self.tipo_cb.setMaxVisibleItems(2)
        self.tipo_cb.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.tipo_cb.setDuplicatesEnabled(False)
        self.tipo_cb.setFrame(True)
        self.tipo_cb.setObjectName("tipo_cb")
        self.tipo_cb.addItem("")
        self.tipo_cb.addItem("")
        self.tipo_cb.addItem("")
        self.tipo_cb.setItemText(2, "")
        self.label_apellido = QtWidgets.QLabel(self.frame_2)
        self.label_apellido.setGeometry(QtCore.QRect(60, 160, 67, 27))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_apellido.setFont(font)
        self.label_apellido.setStyleSheet("font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_apellido.setObjectName("label_apellido")
        self.mail_input = QtWidgets.QLineEdit(self.frame_2)
        self.mail_input.setGeometry(QtCore.QRect(250, 130, 170, 28))
        self.mail_input.setMinimumSize(QtCore.QSize(0, 0))
        self.mail_input.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.mail_input.setFont(font)
        self.mail_input.setStyleSheet("QLineEdit{\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"}\n"
"")
        self.mail_input.setPlaceholderText("")
        self.mail_input.setObjectName("mail_input")
        self.label_mail = QtWidgets.QLabel(self.frame_2)
        self.label_mail.setGeometry(QtCore.QRect(250, 100, 90, 27))
        self.label_mail.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_mail.setFont(font)
        self.label_mail.setStyleSheet("font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_mail.setObjectName("label_mail")
        self.label_password = QtWidgets.QLabel(self.frame_2)
        self.label_password.setGeometry(QtCore.QRect(430, 100, 154, 27))
        self.label_password.setMaximumSize(QtCore.QSize(154, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_password.setObjectName("label_password")
        self.dni_input = QtWidgets.QLineEdit(self.frame_2)
        self.dni_input.setGeometry(QtCore.QRect(60, 70, 170, 28))
        self.dni_input.setMinimumSize(QtCore.QSize(0, 0))
        self.dni_input.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.dni_input.setFont(font)
        self.dni_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"border: none;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"}\n"
"")
        self.dni_input.setPlaceholderText("")
        self.dni_input.setObjectName("dni_input")
        self.label_rep_password = QtWidgets.QLabel(self.frame_2)
        self.label_rep_password.setGeometry(QtCore.QRect(430, 160, 158, 27))
        self.label_rep_password.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_rep_password.setFont(font)
        self.label_rep_password.setStyleSheet("\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_rep_password.setObjectName("label_rep_password")
        self.label_dni = QtWidgets.QLabel(self.frame_2)
        self.label_dni.setGeometry(QtCore.QRect(60, 40, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_dni.setFont(font)
        self.label_dni.setStyleSheet("font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_dni.setObjectName("label_dni")
        self.pass_input = QtWidgets.QLineEdit(self.frame_2)
        self.pass_input.setGeometry(QtCore.QRect(430, 130, 170, 28))
        self.pass_input.setMinimumSize(QtCore.QSize(0, 0))
        self.pass_input.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pass_input.setFont(font)
        self.pass_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"border: none;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"}\n"
"")
        self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_input.setPlaceholderText("")
        self.pass_input.setObjectName("pass_input")
        self.label_tipo = QtWidgets.QLabel(self.frame_2)
        self.label_tipo.setGeometry(QtCore.QRect(430, 40, 90, 27))
        self.label_tipo.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_tipo.setFont(font)
        self.label_tipo.setStyleSheet("font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_tipo.setObjectName("label_tipo")
        self.puesto_input = QtWidgets.QLineEdit(self.frame_2)
        self.puesto_input.setGeometry(QtCore.QRect(250, 70, 170, 28))
        self.puesto_input.setMinimumSize(QtCore.QSize(0, 0))
        self.puesto_input.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.puesto_input.setFont(font)
        self.puesto_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"border: none;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"}\n"
"")
        self.puesto_input.setPlaceholderText("")
        self.puesto_input.setObjectName("puesto_input")
        self.label_nombre = QtWidgets.QLabel(self.frame_2)
        self.label_nombre.setGeometry(QtCore.QRect(60, 100, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_nombre.setFont(font)
        self.label_nombre.setStyleSheet("\n"
"font-size: 14px;\n"
"\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_nombre.setObjectName("label_nombre")
        self.label_puesto = QtWidgets.QLabel(self.frame_2)
        self.label_puesto.setGeometry(QtCore.QRect(250, 40, 84, 27))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_puesto.setFont(font)
        self.label_puesto.setStyleSheet("font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_puesto.setObjectName("label_puesto")
        self.nacimiento_date = QtWidgets.QDateEdit(self.frame_2)
        self.nacimiento_date.setGeometry(QtCore.QRect(60, 240, 170, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.nacimiento_date.setFont(font)
        self.nacimiento_date.setStyleSheet("\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"font-size:12px;\n"
"margin-left: 10px;\n"
"\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;")
        self.nacimiento_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.nacimiento_date.setObjectName("nacimiento_date")
        self.label_nacimiento = QtWidgets.QLabel(self.frame_2)
        self.label_nacimiento.setGeometry(QtCore.QRect(60, 210, 91, 27))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(-1)
        self.label_nacimiento.setFont(font)
        self.label_nacimiento.setStyleSheet("\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_nacimiento.setObjectName("label_nacimiento")
        self.pass_rep_input = QtWidgets.QLineEdit(self.frame_2)
        self.pass_rep_input.setGeometry(QtCore.QRect(430, 190, 170, 28))
        self.pass_rep_input.setMinimumSize(QtCore.QSize(0, 0))
        self.pass_rep_input.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pass_rep_input.setFont(font)
        self.pass_rep_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"border: none;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"}\n"
"")
        self.pass_rep_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_rep_input.setPlaceholderText("")
        self.pass_rep_input.setObjectName("pass_rep_input")
        self.mail_rep_input = QtWidgets.QLineEdit(self.frame_2)
        self.mail_rep_input.setGeometry(QtCore.QRect(250, 190, 170, 28))
        self.mail_rep_input.setMinimumSize(QtCore.QSize(0, 0))
        self.mail_rep_input.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.mail_rep_input.setFont(font)
        self.mail_rep_input.setStyleSheet("QLineEdit{\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"background-color: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"}\n"
"")
        self.mail_rep_input.setPlaceholderText("")
        self.mail_rep_input.setObjectName("mail_rep_input")
        self.subirFoto_btn_2 = QtWidgets.QPushButton(self.frame_2)
        self.subirFoto_btn_2.setGeometry(QtCore.QRect(260, 240, 160, 25))
        self.subirFoto_btn_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setBold(True)
        font.setWeight(75)
        self.subirFoto_btn_2.setFont(font)
        self.subirFoto_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.subirFoto_btn_2.setStyleSheet("QPushButton{\n"
"background-color: #055ffc;\n"
"color:#fff;\n"
"border-radius: 5px;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.subirFoto_btn_2.setObjectName("subirFoto_btn_2")
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tipo_cb.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modificarprod_btn.setText(_translate("MainWindow", "Modificar Usuario"))
        self.eliminarprod_btn.setText(_translate("MainWindow", "Dar De Baja Usuario"))
        self.label_rep_mail.setText(_translate("MainWindow", "Repetir Mail"))
        self.tipo_cb.setCurrentText(_translate("MainWindow", "Usuario"))
        self.tipo_cb.setItemText(0, _translate("MainWindow", "Usuario"))
        self.tipo_cb.setItemText(1, _translate("MainWindow", "Administrador"))
        self.label_apellido.setText(_translate("MainWindow", "Apellido"))
        self.label_mail.setText(_translate("MainWindow", "Mail"))
        self.label_password.setText(_translate("MainWindow", "Contraseña"))
        self.label_rep_password.setText(_translate("MainWindow", "Repetir Contraseña"))
        self.label_dni.setText(_translate("MainWindow", "DNI"))
        self.label_tipo.setText(_translate("MainWindow", "Tipo"))
        self.label_nombre.setText(_translate("MainWindow", "Nombre"))
        self.label_puesto.setText(_translate("MainWindow", "Puesto"))
        self.label_nacimiento.setText(_translate("MainWindow", "Nacimiento"))
        self.subirFoto_btn_2.setText(_translate("MainWindow", "Actualizar Imagen"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
