# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_area.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(396, 262)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-30, 0, 461, 311))
        self.frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background: #fff;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(90, 50, 261, 171))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(240, 242, 255);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.modificar_btn = QtWidgets.QPushButton(self.frame_3)
        self.modificar_btn.setGeometry(QtCore.QRect(70, 110, 111, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.modificar_btn.setFont(font)
        self.modificar_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modificar_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color: #fff;\n"
"border-radius:5px;\n"
"font-family:Roboto;\n"
"font-size: 13px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"}")
        self.modificar_btn.setObjectName("modificar_btn")
        self.label_Area = QtWidgets.QLabel(self.frame_3)
        self.label_Area.setGeometry(QtCore.QRect(76, 30, 111, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.label_Area.setFont(font)
        self.label_Area.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_Area.setObjectName("label_Area")
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(60, 70, 121, 24))
        self.comboBox.setStyleSheet("background-color: #fff;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: rgb(0, 0, 0);\n"
"font-family:Roboto;\n"
"border: none;\n"
"font-size:13px;\n"
"margin-left: 10px;\n"
"")
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eliminar Área"))
        self.modificar_btn.setText(_translate("MainWindow", "Eliminar"))
        self.label_Area.setText(_translate("MainWindow", "Elegir Área"))
from Interfaces.main import img_oficiales_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
