# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_area.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import *
# -*- coding: utf-8 -*-

from CLASES import area as a
from Interfaces.main.delete_area_ui import Ui_MainWindow
# Form implementation generated from reading ui file 'delete_area.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

nombreViejo = ""

from PyQt5 import QtCore, QtGui, QtWidgets

class BorrarArea(QMainWindow):

    def __init__(self):
        super(BorrarArea, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        ############# RECIBIMOS PROPORCIONES DE LA PANTALLA ###########
        qt_rectangle = self.frameGeometry()
        center_point = QDesktopWidget().availableGeometry().center()
        qt_rectangle.moveCenter(center_point)
        self.move(qt_rectangle.topLeft())
        ############## CENTRAMOS LA VENTANA #############
        center_point = QDesktopWidget().availableGeometry().center()
        qt_rectangle.moveCenter(center_point)
        self.move(qt_rectangle.topLeft())
        self.ui.modificar_btn.clicked.connect(lambda: self.eliminar_area())
        self.rellenar_campo()
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(312, 244)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-30, 0, 461, 311))
        self.frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background: #f5f5f5;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(110, 120, 151, 27))
        self.comboBox.setStyleSheet("background-color: #fff;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: rgb(0, 0, 0);\n"
"font-family:Roboto;\n"
"border: none;\n"
"font-size:13px;\n"
"margin-left: 10px;\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.label_Area = QtWidgets.QLabel(self.frame_2)
        self.label_Area.setGeometry(QtCore.QRect(110, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Area.setFont(font)
        self.label_Area.setStyleSheet("\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_Area.setObjectName("label_Area")
        self.modificar_btn = QtWidgets.QPushButton(self.frame_2)
        self.modificar_btn.setGeometry(QtCore.QRect(120, 170, 141, 26))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.modificar_btn.setFont(font)
        self.modificar_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modificar_btn.setStyleSheet("QPushButton{\n"
"background-color: #055ffc;\n"
"color:#fff;\n"
"border-radius: 5px;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.modificar_btn.setObjectName("modificar_btn")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #212325;\n"
"margin-bottom: 5px")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

    def eliminar_area(self):
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        area = self.ui.comboBox.currentText()
        qm = QMessageBox

        ret = qm.warning(self, 'Esta acción es irreversible', "¿Estás seguro que quieres eliminar ésta área ?",
                         qm.Yes | qm.No)
        if ret == qm.Yes:
            a.Area.eliminar_area(area)
            self.close()

    def rellenar_campo(self):
        areas = a.Area.listar_area()
        for area in areas:
            self.ui.comboBox.addItem(area[0])
        self.close()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Area.setText(_translate("MainWindow", "Elegir Área"))
        self.modificar_btn.setText(_translate("MainWindow", "Eliminar"))
        self.label_5.setText(_translate("MainWindow", "Eliminar Área"))
