# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'egreso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 261)
        MainWindow.setMaximumSize(QtCore.QSize(475, 261))
        MainWindow.setToolTipDuration(0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 475, 296))
        self.frame_2.setMinimumSize(QtCore.QSize(0, 237))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_2.setStyleSheet("background: #fff;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 455, 242))
        self.frame_4.setMinimumSize(QtCore.QSize(435, 242))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_4.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(240, 242, 255);\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_fecha_3 = QtWidgets.QLabel(self.frame_4)
        self.label_fecha_3.setGeometry(QtCore.QRect(230, 30, 131, 27))
        self.label_fecha_3.setMaximumSize(QtCore.QSize(174, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(0)
        self.label_fecha_3.setFont(font)
        self.label_fecha_3.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_fecha_3.setObjectName("label_fecha_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 62, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(0)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.codigo_producto_input_2 = QtWidgets.QLineEdit(self.frame_4)
        self.codigo_producto_input_2.setGeometry(QtCore.QRect(20, 60, 170, 25))
        self.codigo_producto_input_2.setMinimumSize(QtCore.QSize(0, 0))
        self.codigo_producto_input_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.codigo_producto_input_2.setStyleSheet("QLineEdit{\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"}\n"
"")
        self.codigo_producto_input_2.setPlaceholderText("")
        self.codigo_producto_input_2.setObjectName("codigo_producto_input_2")
        self.label_codigo_producto_2 = QtWidgets.QLabel(self.frame_4)
        self.label_codigo_producto_2.setGeometry(QtCore.QRect(20, 30, 141, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(0)
        self.label_codigo_producto_2.setFont(font)
        self.label_codigo_producto_2.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_codigo_producto_2.setObjectName("label_codigo_producto_2")
        self.crear_egreso = QtWidgets.QPushButton(self.frame_4)
        self.crear_egreso.setGeometry(QtCore.QRect(150, 180, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(0)
        self.crear_egreso.setFont(font)
        self.crear_egreso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crear_egreso.setStyleSheet("QPushButton{\n"
"background-color: rgba(71, 71, 103);\n"
"color: #fff;\n"
"border-radius:5px;\n"
"font-family:Roboto;\n"
"font-size: 13px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"}")
        self.crear_egreso.setObjectName("crear_egreso")
        self.fecha_egreso = QtWidgets.QDateEdit(self.frame_4)
        self.fecha_egreso.setGeometry(QtCore.QRect(230, 60, 170, 25))
        self.fecha_egreso.setStyleSheet("\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #000;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"")
        self.fecha_egreso.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.fecha_egreso.setObjectName("fecha_egreso")
        self.label_cantidad_2 = QtWidgets.QLabel(self.frame_4)
        self.label_cantidad_2.setGeometry(QtCore.QRect(20, 90, 141, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(0)
        self.label_cantidad_2.setFont(font)
        self.label_cantidad_2.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_cantidad_2.setObjectName("label_cantidad_2")
        self.cantidad = QtWidgets.QSpinBox(self.frame_4)
        self.cantidad.setGeometry(QtCore.QRect(20, 120, 170, 25))
        self.cantidad.setStyleSheet("\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"\n"
"")
        self.cantidad.setObjectName("cantidad")
        self.motivo_input_2 = QtWidgets.QLineEdit(self.frame_4)
        self.motivo_input_2.setGeometry(QtCore.QRect(230, 120, 170, 25))
        self.motivo_input_2.setMinimumSize(QtCore.QSize(0, 0))
        self.motivo_input_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.motivo_input_2.setStyleSheet("QLineEdit{\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"}\n"
"")
        self.motivo_input_2.setPlaceholderText("")
        self.motivo_input_2.setObjectName("motivo_input_2")
        self.label_codigo_producto_3 = QtWidgets.QLabel(self.frame_4)
        self.label_codigo_producto_3.setGeometry(QtCore.QRect(230, 90, 141, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(0)
        self.label_codigo_producto_3.setFont(font)
        self.label_codigo_producto_3.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_codigo_producto_3.setObjectName("label_codigo_producto_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nuevo Egreso"))
        self.label_fecha_3.setText(_translate("MainWindow", "Fecha de Egreso"))
        self.label_codigo_producto_2.setText(_translate("MainWindow", "Código de producto"))
        self.crear_egreso.setText(_translate("MainWindow", "Confirmar"))
        self.label_cantidad_2.setText(_translate("MainWindow", "Cantidad"))
        self.label_codigo_producto_3.setText(_translate("MainWindow", "Motivo"))
from Interfaces.main import img_oficiales_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
