# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mordern.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 686)
        MainWindow.setMinimumSize(QtCore.QSize(0, 686))
        MainWindow.setMaximumSize(QtCore.QSize(1150, 686))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setStyleSheet("background-color: #f7f7f7;\n"
"border:none;")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_frame = QtWidgets.QFrame(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_frame.sizePolicy().hasHeightForWidth())
        self.left_frame.setSizePolicy(sizePolicy)
        self.left_frame.setMinimumSize(QtCore.QSize(233, 0))
        self.left_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.left_frame.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.left_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.left_frame)
        self.frame_7.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.products_btn = QtWidgets.QPushButton(self.frame_9)
        self.products_btn.setGeometry(QtCore.QRect(5, 109, 50, 71))
        self.products_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.products_btn.setFont(font)
        self.products_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.products_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"font-family: Roboto;\n"
"border-radius:5px;\n"
"margin-top: 20px 0 ;\n"
"color: #282830 ;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(105, 105, 226, 50);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(0,0,0);\n"
"}")
        self.products_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/caja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.products_btn.setIcon(icon)
        self.products_btn.setIconSize(QtCore.QSize(50, 50))
        self.products_btn.setObjectName("products_btn")
        self.exit_btn = QtWidgets.QPushButton(self.frame_9)
        self.exit_btn.setGeometry(QtCore.QRect(0, 641, 50, 41))
        self.exit_btn.setMaximumSize(QtCore.QSize(50, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"padding-right:30px;\n"
"font-family: Roboto;\n"
"text-align: left;\n"
"border-radius:5px;\n"
"margin-bottom:5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(105, 105, 226, 50);\n"
"}")
        self.exit_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/ExitB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon1)
        self.exit_btn.setIconSize(QtCore.QSize(50, 50))
        self.exit_btn.setObjectName("exit_btn")
        self.deposito_btn = QtWidgets.QPushButton(self.frame_9)
        self.deposito_btn.setGeometry(QtCore.QRect(5, 200, 50, 71))
        self.deposito_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        self.deposito_btn.setFont(font)
        self.deposito_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deposito_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:5px;\n"
"margin-top: 20px;\n"
"font-family: Roboto;\n"
"color: #282830 ;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(105, 105, 226, 50);\n"
"}")
        self.deposito_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/stock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deposito_btn.setIcon(icon2)
        self.deposito_btn.setIconSize(QtCore.QSize(30, 30))
        self.deposito_btn.setObjectName("deposito_btn")
        self.pushButton = QtWidgets.QPushButton(self.frame_9)
        self.pushButton.setGeometry(QtCore.QRect(5, 26, 50, 51))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setStyleSheet("margin: 50px 30;\n"
"border:none;\n"
"")
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/Warehouse Bull Soft Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(45, 45))
        self.pushButton.setObjectName("pushButton")
        self.users_btn = QtWidgets.QPushButton(self.frame_9)
        self.users_btn.setGeometry(QtCore.QRect(5, 300, 50, 70))
        self.users_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.users_btn.setFont(font)
        self.users_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.users_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"font-family: Roboto;\n"
"border-radius:5px;\n"
"margin-top: 5px  ;\n"
"color: #282830 ;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(105, 105, 226, 50);\n"
"\n"
"}")
        self.users_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.users_btn.setIcon(icon4)
        self.users_btn.setIconSize(QtCore.QSize(30, 30))
        self.users_btn.setObjectName("users_btn")
        self.verticalLayout.addWidget(self.frame_9)
        self.horizontalLayout_9.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.left_frame)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(170, 16777215))
        self.frame_8.setStyleSheet("margin-left:5px;\n"
"border-left:1px solid #cccccc;\n"
"border-right:1px solid #cccccc;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget_3.setStyleSheet("border:none")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.product_subpage = QtWidgets.QWidget()
        self.product_subpage.setObjectName("product_subpage")
        self.label_7 = QtWidgets.QLabel(self.product_subpage)
        self.label_7.setGeometry(QtCore.QRect(10, 32, 128, 40))
        self.label_7.setMinimumSize(QtCore.QSize(128, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #282830 ;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.products_btn_stock = QtWidgets.QPushButton(self.product_subpage)
        self.products_btn_stock.setGeometry(QtCore.QRect(20, 140, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.products_btn_stock.setFont(font)
        self.products_btn_stock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.products_btn_stock.setStyleSheet("QPushButton{\n"
"border:none;\n"
"font-family: Roboto;\n"
"border-radius:5px;\n"
"text-align: left;\n"
"color: #282830 ;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(105, 105, 226, 50);\n"
"}")
        self.products_btn_stock.setIconSize(QtCore.QSize(30, 30))
        self.products_btn_stock.setObjectName("products_btn_stock")
        self.products_btn_movimiento = QtWidgets.QPushButton(self.product_subpage)
        self.products_btn_movimiento.setGeometry(QtCore.QRect(20, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.products_btn_movimiento.setFont(font)
        self.products_btn_movimiento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.products_btn_movimiento.setStyleSheet("QPushButton{\n"
"border:none;\n"
"font-family: Roboto;\n"
"text-align:left;\n"
"color: #282830 ;\n"
"border-radius:5px;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(105, 105, 226, 50);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    background-color: rgba(105, 105, 226, 50);\n"
"}")
        self.products_btn_movimiento.setIconSize(QtCore.QSize(30, 35))
        self.products_btn_movimiento.setObjectName("products_btn_movimiento")
        self.products_btn_lotes = QtWidgets.QPushButton(self.product_subpage)
        self.products_btn_lotes.setGeometry(QtCore.QRect(20, 240, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.products_btn_lotes.setFont(font)
        self.products_btn_lotes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.products_btn_lotes.setStyleSheet("QPushButton{\n"
"border:none;\n"
"font-family: Roboto;\n"
"text-align:left;\n"
"color: #282830 ;\n"
"border-radius:5px;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(105, 105, 226, 50);\n"
"}")
        self.products_btn_lotes.setIconSize(QtCore.QSize(30, 35))
        self.products_btn_lotes.setObjectName("products_btn_lotes")
        self.stackedWidget_3.addWidget(self.product_subpage)
        self.deposito_subpage = QtWidgets.QWidget()
        self.deposito_subpage.setObjectName("deposito_subpage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.deposito_subpage)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.deposito_subpage)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.frame_6)
        self.frame_13.setMaximumSize(QtCore.QSize(200, 100))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setGeometry(QtCore.QRect(7, 30, 128, 40))
        self.label_9.setMinimumSize(QtCore.QSize(128, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #282830 ;\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.frame_13)
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setMinimumSize(QtCore.QSize(128, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_12.setStyleSheet("color: #282830 ;\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.frame_14 = QtWidgets.QFrame(self.frame_6)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.frame_14)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.stackedWidget_3.addWidget(self.deposito_subpage)
        self.user_subpage = QtWidgets.QWidget()
        self.user_subpage.setObjectName("user_subpage")
        self.label_10 = QtWidgets.QLabel(self.user_subpage)
        self.label_10.setGeometry(QtCore.QRect(10, 32, 128, 40))
        self.label_10.setMinimumSize(QtCore.QSize(128, 0))
        self.label_10.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #282830 ;\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.stackedWidget_3.addWidget(self.user_subpage)
        self.horizontalLayout_10.addWidget(self.stackedWidget_3)
        self.horizontalLayout_9.addWidget(self.frame_8)
        self.horizontalLayout.addWidget(self.left_frame)
        self.frame = QtWidgets.QFrame(self.container)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_stock = QtWidgets.QWidget()
        self.page_stock.setObjectName("page_stock")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_stock)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.container_stock_3 = QtWidgets.QFrame(self.page_stock)
        self.container_stock_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_stock_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_stock_3.setObjectName("container_stock_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.container_stock_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.top_frame_stock_3 = QtWidgets.QFrame(self.container_stock_3)
        self.top_frame_stock_3.setMinimumSize(QtCore.QSize(0, 80))
        self.top_frame_stock_3.setMaximumSize(QtCore.QSize(300, 70))
        self.top_frame_stock_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_stock_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_stock_3.setObjectName("top_frame_stock_3")
        self.frame_10 = QtWidgets.QFrame(self.top_frame_stock_3)
        self.frame_10.setGeometry(QtCore.QRect(0, 13, 354, 70))
        self.frame_10.setMinimumSize(QtCore.QSize(354, 70))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_10)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(80, 10, 120, 52))
        self.label_8.setMinimumSize(QtCore.QSize(66, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #282830 ;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 9, 49, 40))
        self.pushButton_13.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_13.setStyleSheet("margin-left:5px")
        self.pushButton_13.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/warehouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon5)
        self.pushButton_13.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_23.addWidget(self.groupBox_4)
        self.product_new_btn = QtWidgets.QPushButton(self.top_frame_stock_3)
        self.product_new_btn.setGeometry(QtCore.QRect(160, 35, 131, 26))
        self.product_new_btn.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.product_new_btn.setFont(font)
        self.product_new_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.product_new_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color:#fff;\n"
"padding-right:15px;\n"
"border-radius: 5px;\n"
"text-align:right;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.product_new_btn.setIcon(icon6)
        self.product_new_btn.setIconSize(QtCore.QSize(13, 13))
        self.product_new_btn.setObjectName("product_new_btn")
        self.verticalLayout_5.addWidget(self.top_frame_stock_3)
        self.mid_stock_3 = QtWidgets.QFrame(self.container_stock_3)
        self.mid_stock_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.mid_stock_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_stock_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_stock_3.setObjectName("mid_stock_3")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.mid_stock_3)
        self.verticalLayout_24.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_11 = QtWidgets.QFrame(self.mid_stock_3)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_11)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_7.setStyleSheet("margin-left: 14px")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.btn_buscarP = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_buscarP.setGeometry(QtCore.QRect(18, 9, 32, 21))
        self.btn_buscarP.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_buscarP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_buscarP.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/LupaB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscarP.setIcon(icon7)
        self.btn_buscarP.setIconSize(QtCore.QSize(50, 50))
        self.btn_buscarP.setObjectName("btn_buscarP")
        self.buscar_input = QtWidgets.QLineEdit(self.groupBox_7)
        self.buscar_input.setGeometry(QtCore.QRect(50, 10, 301, 20))
        self.buscar_input.setMinimumSize(QtCore.QSize(0, 20))
        self.buscar_input.setStyleSheet("font-family: Roboto;\n"
"")
        self.buscar_input.setText("")
        self.buscar_input.setObjectName("buscar_input")
        self.verticalLayout_25.addWidget(self.groupBox_7)
        self.verticalLayout_24.addWidget(self.frame_11, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_5.addWidget(self.mid_stock_3)
        self.bottom_stock_3 = QtWidgets.QFrame(self.container_stock_3)
        self.bottom_stock_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_stock_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_stock_3.setObjectName("bottom_stock_3")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.bottom_stock_3)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_19 = QtWidgets.QFrame(self.bottom_stock_3)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.tableWidget_stock_2 = QtWidgets.QTableWidget(self.frame_19)
        self.tableWidget_stock_2.setGeometry(QtCore.QRect(30, 60, 851, 422))
        self.tableWidget_stock_2.setMaximumSize(QtCore.QSize(16777215, 422))
        self.tableWidget_stock_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_stock_2.setStyleSheet("QTableWidget{\n"
"font-size: 11pt;\n"
"margin-left: 0px;\n"
"margin-top:15px;\n"
"color: #000;\n"
"font-family: Roboto;\n"
"text-align:center;\n"
"}\n"
"QheaderView::item\n"
"    {\n"
"text-align:center;\n"
"\n"
"    }\n"
"QHeaderView::section {\n"
"    background-color: #394353;\n"
"    border-radius: 11px;\n"
"    color:#fff;\n"
"    font-size: 9pt;\n"
"    font-family:Roboto;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #394353;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"\n"
"    border-left: 1px solid #394353;\n"
"}")
        self.tableWidget_stock_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_stock_2.setShowGrid(False)
        self.tableWidget_stock_2.setObjectName("tableWidget_stock_2")
        self.tableWidget_stock_2.setColumnCount(5)
        self.tableWidget_stock_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stock_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_stock_2.horizontalHeader().setVisible(False)
        self.tableWidget_stock_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_stock_2.horizontalHeader().setDefaultSectionSize(169)
        self.tableWidget_stock_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_stock_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_stock_2.verticalHeader().setVisible(False)
        self.tableWidget_stock_2.verticalHeader().setDefaultSectionSize(41)
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setGeometry(QtCore.QRect(20, 9, 861, 41))
        self.frame_20.setMinimumSize(QtCore.QSize(56, 41))
        self.frame_20.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius:15px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11, 0, QtCore.Qt.AlignLeft)
        self.label_23 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"\n"
"")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23, 0, QtCore.Qt.AlignLeft)
        self.label_24 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_15.addWidget(self.label_24, 0, QtCore.Qt.AlignLeft)
        self.label_25 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25, 0, QtCore.Qt.AlignLeft)
        self.label_26 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26, 0, QtCore.Qt.AlignLeft)
        self.btn_actualizarStock = QtWidgets.QPushButton(self.frame_19)
        self.btn_actualizarStock.setGeometry(QtCore.QRect(883, 20, 31, 21))
        self.btn_actualizarStock.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_actualizarStock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizarStock.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_actualizarStock.setIcon(icon8)
        self.btn_actualizarStock.setIconSize(QtCore.QSize(33, 16))
        self.btn_actualizarStock.setObjectName("btn_actualizarStock")
        self.verticalLayout_26.addWidget(self.frame_19)
        self.verticalLayout_5.addWidget(self.bottom_stock_3)
        self.horizontalLayout_3.addWidget(self.container_stock_3)
        self.stackedWidget_main.addWidget(self.page_stock)
        self.page_movimientos = QtWidgets.QWidget()
        self.page_movimientos.setObjectName("page_movimientos")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_movimientos)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.container_mov_2 = QtWidgets.QFrame(self.page_movimientos)
        self.container_mov_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_mov_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_mov_2.setObjectName("container_mov_2")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.container_mov_2)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.top_frame_mov_2 = QtWidgets.QFrame(self.container_mov_2)
        self.top_frame_mov_2.setMinimumSize(QtCore.QSize(1, 80))
        self.top_frame_mov_2.setMaximumSize(QtCore.QSize(555, 70))
        self.top_frame_mov_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_mov_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_mov_2.setObjectName("top_frame_mov_2")
        self.frame_12 = QtWidgets.QFrame(self.top_frame_mov_2)
        self.frame_12.setGeometry(QtCore.QRect(0, 13, 681, 70))
        self.frame_12.setMinimumSize(QtCore.QSize(354, 70))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_12)
        self.groupBox_8.setMinimumSize(QtCore.QSize(384, 0))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(80, 10, 152, 52))
        self.label_27.setMinimumSize(QtCore.QSize(152, 0))
        self.label_27.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: #282830 ;\n"
"")
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 9, 49, 40))
        self.pushButton_16.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_16.setStyleSheet("margin-left:5px")
        self.pushButton_16.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/trading.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon9)
        self.pushButton_16.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_16.setObjectName("pushButton_16")
        self.new_ingreso_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.new_ingreso_btn.setGeometry(QtCore.QRect(250, 22, 81, 26))
        self.new_ingreso_btn.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.new_ingreso_btn.setFont(font)
        self.new_ingreso_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_ingreso_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color:#fff;\n"
"padding-right:15px;\n"
"border-radius: 5px;\n"
"text-align:right;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"\n"
"}")
        self.new_ingreso_btn.setIcon(icon6)
        self.new_ingreso_btn.setIconSize(QtCore.QSize(13, 13))
        self.new_ingreso_btn.setObjectName("new_ingreso_btn")
        self.new_egreso_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.new_egreso_btn.setGeometry(QtCore.QRect(351, 23, 81, 26))
        self.new_egreso_btn.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.new_egreso_btn.setFont(font)
        self.new_egreso_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_egreso_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color:#fff;\n"
"padding-right:15px;\n"
"border-radius: 5px;\n"
"text-align:right;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"\n"
"}")
        self.new_egreso_btn.setIcon(icon6)
        self.new_egreso_btn.setIconSize(QtCore.QSize(13, 13))
        self.new_egreso_btn.setObjectName("new_egreso_btn")
        self.verticalLayout_29.addWidget(self.groupBox_8)
        self.verticalLayout_27.addWidget(self.top_frame_mov_2)
        self.mid_mov_2 = QtWidgets.QFrame(self.container_mov_2)
        self.mid_mov_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.mid_mov_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_mov_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_mov_2.setObjectName("mid_mov_2")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.mid_mov_2)
        self.verticalLayout_30.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_21 = QtWidgets.QFrame(self.mid_mov_2)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame_21)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_9.setStyleSheet("margin-left: 14px")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_18.setGeometry(QtCore.QRect(18, 9, 31, 21))
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 21))
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setText("")
        self.pushButton_18.setIcon(icon7)
        self.pushButton_18.setIconSize(QtCore.QSize(52, 82))
        self.pushButton_18.setObjectName("pushButton_18")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 10, 311, 20))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_5.setStyleSheet("font-family: Roboto;\n"
"")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_31.addWidget(self.groupBox_9)
        self.verticalLayout_30.addWidget(self.frame_21, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_27.addWidget(self.mid_mov_2)
        self.bottom_mov_2 = QtWidgets.QFrame(self.container_mov_2)
        self.bottom_mov_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_mov_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_mov_2.setObjectName("bottom_mov_2")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.bottom_mov_2)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_22 = QtWidgets.QFrame(self.bottom_mov_2)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.tableWidget_movimientos_2 = QtWidgets.QTableWidget(self.frame_22)
        self.tableWidget_movimientos_2.setGeometry(QtCore.QRect(40, 50, 921, 371))
        self.tableWidget_movimientos_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_movimientos_2.setStyleSheet("QTableWidget{\n"
"font-size: 11pt;\n"
"margin-top:15px;\n"
"color: #000;\n"
"font-family: Roboto;\n"
"text-align:center;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #394353;\n"
"    border-radius: 11px;\n"
"    color:#fff;\n"
"    font-size: 9pt;\n"
"    font-family:Roboto;\n"
"    border-left: 1px solid #394353;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #394353;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"\n"
"    border-left: 1px solid #394353;\n"
"}")
        self.tableWidget_movimientos_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_movimientos_2.setShowGrid(False)
        self.tableWidget_movimientos_2.setObjectName("tableWidget_movimientos_2")
        self.tableWidget_movimientos_2.setColumnCount(6)
        self.tableWidget_movimientos_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_movimientos_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_movimientos_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_movimientos_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_movimientos_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_movimientos_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_movimientos_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_movimientos_2.horizontalHeader().setVisible(False)
        self.tableWidget_movimientos_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_movimientos_2.horizontalHeader().setDefaultSectionSize(135)
        self.tableWidget_movimientos_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_movimientos_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_movimientos_2.verticalHeader().setVisible(False)
        self.tableWidget_movimientos_2.verticalHeader().setDefaultSectionSize(41)
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setGeometry(QtCore.QRect(29, 9, 831, 41))
        self.frame_23.setMinimumSize(QtCore.QSize(56, 41))
        self.frame_23.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius:15px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_28 = QtWidgets.QLabel(self.frame_23)
        self.label_28.setGeometry(QtCore.QRect(20, 10, 47, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_23)
        self.label_29.setGeometry(QtCore.QRect(130, 10, 79, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"\n"
"")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_23)
        self.label_30.setGeometry(QtCore.QRect(410, 10, 132, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_30.setObjectName("label_30")
        self.label_32 = QtWidgets.QLabel(self.frame_23)
        self.label_32.setGeometry(QtCore.QRect(690, 10, 71, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"text-align:left;\n"
"")
        self.label_32.setObjectName("label_32")
        self.label_31 = QtWidgets.QLabel(self.frame_23)
        self.label_31.setGeometry(QtCore.QRect(570, 10, 80, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.frame_23)
        self.label_33.setGeometry(QtCore.QRect(280, 10, 61, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"\n"
"")
        self.label_33.setObjectName("label_33")
        self.btn_actualizarMov = QtWidgets.QPushButton(self.frame_22)
        self.btn_actualizarMov.setGeometry(QtCore.QRect(870, 20, 31, 21))
        self.btn_actualizarMov.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_actualizarMov.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizarMov.setText("")
        self.btn_actualizarMov.setIcon(icon8)
        self.btn_actualizarMov.setIconSize(QtCore.QSize(33, 16))
        self.btn_actualizarMov.setObjectName("btn_actualizarMov")
        self.verticalLayout_32.addWidget(self.frame_22)
        self.verticalLayout_27.addWidget(self.bottom_mov_2)
        self.horizontalLayout_4.addWidget(self.container_mov_2)
        self.stackedWidget_main.addWidget(self.page_movimientos)
        self.page_lotes = QtWidgets.QWidget()
        self.page_lotes.setObjectName("page_lotes")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_lotes)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.container_mov_3 = QtWidgets.QFrame(self.page_lotes)
        self.container_mov_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_mov_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_mov_3.setObjectName("container_mov_3")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.container_mov_3)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.top_frame_mov_3 = QtWidgets.QFrame(self.container_mov_3)
        self.top_frame_mov_3.setMinimumSize(QtCore.QSize(1, 80))
        self.top_frame_mov_3.setMaximumSize(QtCore.QSize(387, 70))
        self.top_frame_mov_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_mov_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_mov_3.setObjectName("top_frame_mov_3")
        self.frame_26 = QtWidgets.QFrame(self.top_frame_mov_3)
        self.frame_26.setGeometry(QtCore.QRect(0, 13, 431, 70))
        self.frame_26.setMinimumSize(QtCore.QSize(354, 70))
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.groupBox_10 = QtWidgets.QGroupBox(self.frame_26)
        self.groupBox_10.setMinimumSize(QtCore.QSize(384, 0))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_40 = QtWidgets.QLabel(self.groupBox_10)
        self.label_40.setGeometry(QtCore.QRect(80, 10, 152, 52))
        self.label_40.setMinimumSize(QtCore.QSize(152, 0))
        self.label_40.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: #282830 ;\n"
"")
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 9, 49, 40))
        self.pushButton_17.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_17.setStyleSheet("margin-left:5px")
        self.pushButton_17.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/producto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon10)
        self.pushButton_17.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_35.addWidget(self.groupBox_10)
        self.verticalLayout_34.addWidget(self.top_frame_mov_3)
        self.mid_mov_3 = QtWidgets.QFrame(self.container_mov_3)
        self.mid_mov_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.mid_mov_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_mov_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_mov_3.setObjectName("mid_mov_3")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.mid_mov_3)
        self.verticalLayout_36.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.frame_27 = QtWidgets.QFrame(self.mid_mov_3)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_27)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_11.setStyleSheet("margin-left: 14px")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_19.setGeometry(QtCore.QRect(18, 9, 31, 21))
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 21))
        self.pushButton_19.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_19.setText("")
        self.pushButton_19.setIcon(icon7)
        self.pushButton_19.setIconSize(QtCore.QSize(52, 82))
        self.pushButton_19.setObjectName("pushButton_19")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 10, 301, 20))
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_6.setStyleSheet("font-family: Roboto;\n"
"")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_37.addWidget(self.groupBox_11)
        self.verticalLayout_36.addWidget(self.frame_27, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_34.addWidget(self.mid_mov_3)
        self.bottom_mov_3 = QtWidgets.QFrame(self.container_mov_3)
        self.bottom_mov_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_mov_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_mov_3.setObjectName("bottom_mov_3")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.bottom_mov_3)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.frame_28 = QtWidgets.QFrame(self.bottom_mov_3)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.tableWidget_lotes = QtWidgets.QTableWidget(self.frame_28)
        self.tableWidget_lotes.setGeometry(QtCore.QRect(50, 60, 801, 421))
        self.tableWidget_lotes.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_lotes.setStyleSheet("QTableWidget{\n"
"font-size: 11pt;\n"
"margin-top:15px;\n"
"color: #000;\n"
"font-family: Roboto;\n"
"text-align:center;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #394353;\n"
"    border-radius: 11px;\n"
"    color:#fff;\n"
"    font-size: 9pt;\n"
"    font-family:Roboto;\n"
"    border-left: 1px solid #394353;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #394353;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"\n"
"    border-left: 1px solid #394353;\n"
"}")
        self.tableWidget_lotes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_lotes.setShowGrid(False)
        self.tableWidget_lotes.setObjectName("tableWidget_lotes")
        self.tableWidget_lotes.setColumnCount(5)
        self.tableWidget_lotes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lotes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lotes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lotes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lotes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lotes.setHorizontalHeaderItem(4, item)
        self.tableWidget_lotes.horizontalHeader().setVisible(False)
        self.tableWidget_lotes.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_lotes.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_lotes.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_lotes.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_lotes.verticalHeader().setVisible(False)
        self.tableWidget_lotes.verticalHeader().setDefaultSectionSize(41)
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setGeometry(QtCore.QRect(29, 9, 831, 41))
        self.frame_29.setMinimumSize(QtCore.QSize(56, 41))
        self.frame_29.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius:15px;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.label_41 = QtWidgets.QLabel(self.frame_29)
        self.label_41.setGeometry(QtCore.QRect(20, 10, 141, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_29)
        self.label_42.setGeometry(QtCore.QRect(200, 10, 79, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"\n"
"")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_29)
        self.label_43.setGeometry(QtCore.QRect(520, 10, 132, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_43.setObjectName("label_43")
        self.label_45 = QtWidgets.QLabel(self.frame_29)
        self.label_45.setGeometry(QtCore.QRect(650, 10, 161, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_29)
        self.label_46.setGeometry(QtCore.QRect(350, 10, 61, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"\n"
"")
        self.label_46.setObjectName("label_46")
        self.btn_actualizarLotes = QtWidgets.QPushButton(self.frame_28)
        self.btn_actualizarLotes.setGeometry(QtCore.QRect(860, 20, 31, 21))
        self.btn_actualizarLotes.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_actualizarLotes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizarLotes.setText("")
        self.btn_actualizarLotes.setIcon(icon8)
        self.btn_actualizarLotes.setIconSize(QtCore.QSize(33, 16))
        self.btn_actualizarLotes.setObjectName("btn_actualizarLotes")
        self.verticalLayout_38.addWidget(self.frame_28)
        self.verticalLayout_34.addWidget(self.bottom_mov_3)
        self.horizontalLayout_6.addWidget(self.container_mov_3)
        self.stackedWidget_main.addWidget(self.page_lotes)
        self.page_deposito = QtWidgets.QWidget()
        self.page_deposito.setObjectName("page_deposito")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_deposito)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.page_deposito)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(100, 120, 650, 491))
        self.frame_3.setMinimumSize(QtCore.QSize(600, 250))
        self.frame_3.setMaximumSize(QtCore.QSize(650, 500))
        self.frame_3.setStyleSheet("border: 2px solid black;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.top_frame_stock_4 = QtWidgets.QFrame(self.frame_2)
        self.top_frame_stock_4.setGeometry(QtCore.QRect(0, 0, 431, 80))
        self.top_frame_stock_4.setMinimumSize(QtCore.QSize(0, 80))
        self.top_frame_stock_4.setMaximumSize(QtCore.QSize(439, 70))
        self.top_frame_stock_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_stock_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_stock_4.setObjectName("top_frame_stock_4")
        self.frame_24 = QtWidgets.QFrame(self.top_frame_stock_4)
        self.frame_24.setGeometry(QtCore.QRect(0, 13, 681, 70))
        self.frame_24.setMinimumSize(QtCore.QSize(354, 70))
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_24)
        self.groupBox_5.setMinimumSize(QtCore.QSize(429, 0))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(90, 10, 81, 51))
        self.label_34.setMinimumSize(QtCore.QSize(66, 0))
        self.label_34.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: #282830 ;\n"
"")
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 10, 49, 40))
        self.pushButton_11.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_11.setStyleSheet("margin-left:5px")
        self.pushButton_11.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/rack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon11)
        self.pushButton_11.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_11.setObjectName("pushButton_11")
        self.newArea_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.newArea_btn.setGeometry(QtCore.QRect(200, 20, 101, 31))
        self.newArea_btn.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.newArea_btn.setFont(font)
        self.newArea_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newArea_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color:#fff;\n"
"padding-left:10px;\n"
"border-radius: 5px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"\n"
"}")
        self.newArea_btn.setIcon(icon6)
        self.newArea_btn.setIconSize(QtCore.QSize(13, 13))
        self.newArea_btn.setObjectName("newArea_btn")
        self.newArea_btn_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.newArea_btn_2.setGeometry(QtCore.QRect(320, 20, 111, 31))
        self.newArea_btn_2.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.newArea_btn_2.setFont(font)
        self.newArea_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newArea_btn_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color:#fff;\n"
"padding-left:10px;\n"
"border-radius: 5px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"\n"
"}")
        self.newArea_btn_2.setIcon(icon6)
        self.newArea_btn_2.setIconSize(QtCore.QSize(13, 13))
        self.newArea_btn_2.setObjectName("newArea_btn_2")
        self.verticalLayout_33.addWidget(self.groupBox_5)
        self.btn_actualizarAreas = QtWidgets.QPushButton(self.frame_2)
        self.btn_actualizarAreas.setGeometry(QtCore.QRect(450, 40, 31, 21))
        self.btn_actualizarAreas.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_actualizarAreas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizarAreas.setText("")
        self.btn_actualizarAreas.setIcon(icon8)
        self.btn_actualizarAreas.setIconSize(QtCore.QSize(33, 16))
        self.btn_actualizarAreas.setObjectName("btn_actualizarAreas")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.stackedWidget_main.addWidget(self.page_deposito)
        self.page_usuarios = QtWidgets.QWidget()
        self.page_usuarios.setObjectName("page_usuarios")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.page_usuarios)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.stackedWidget_user = QtWidgets.QStackedWidget(self.page_usuarios)
        self.stackedWidget_user.setObjectName("stackedWidget_user")
        self.page_usuarios2 = QtWidgets.QWidget()
        self.page_usuarios2.setObjectName("page_usuarios2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_usuarios2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.container_stock_2 = QtWidgets.QFrame(self.page_usuarios2)
        self.container_stock_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_stock_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_stock_2.setObjectName("container_stock_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.container_stock_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.top_frame_stock_2 = QtWidgets.QFrame(self.container_stock_2)
        self.top_frame_stock_2.setMinimumSize(QtCore.QSize(0, 80))
        self.top_frame_stock_2.setMaximumSize(QtCore.QSize(346, 70))
        self.top_frame_stock_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_stock_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_stock_2.setObjectName("top_frame_stock_2")
        self.frame_15 = QtWidgets.QFrame(self.top_frame_stock_2)
        self.frame_15.setGeometry(QtCore.QRect(0, 13, 391, 70))
        self.frame_15.setMinimumSize(QtCore.QSize(354, 70))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_15)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(90, 10, 120, 52))
        self.label_17.setMinimumSize(QtCore.QSize(66, 0))
        self.label_17.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #282830 ;\n"
"")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(23, 9, 49, 40))
        self.pushButton_10.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_10.setStyleSheet("margin-left:5px")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.user_new_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.user_new_btn.setGeometry(QtCore.QRect(194, 24, 121, 26))
        self.user_new_btn.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.user_new_btn.setFont(font)
        self.user_new_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.user_new_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color:#fff;\n"
"padding-right:15px;\n"
"border-radius: 5px;\n"
"text-align:right;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"\n"
"}")
        self.user_new_btn.setIcon(icon6)
        self.user_new_btn.setIconSize(QtCore.QSize(13, 13))
        self.user_new_btn.setObjectName("user_new_btn")
        self.verticalLayout_18.addWidget(self.groupBox_3)
        self.verticalLayout_17.addWidget(self.top_frame_stock_2)
        self.mid_stock_2 = QtWidgets.QFrame(self.container_stock_2)
        self.mid_stock_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.mid_stock_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_stock_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_stock_2.setObjectName("mid_stock_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.mid_stock_2)
        self.verticalLayout_19.setContentsMargins(0, 30, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_16 = QtWidgets.QFrame(self.mid_stock_2)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_16)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_6.setStyleSheet("margin-left: 14px")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.btn_buscarU = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_buscarU.setGeometry(QtCore.QRect(18, 9, 32, 21))
        self.btn_buscarU.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_buscarU.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_buscarU.setText("")
        self.btn_buscarU.setIcon(icon7)
        self.btn_buscarU.setIconSize(QtCore.QSize(60, 47))
        self.btn_buscarU.setObjectName("btn_buscarU")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 9, 301, 20))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_3.setStyleSheet("font-family: Roboto;\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_20.addWidget(self.groupBox_6)
        self.verticalLayout_19.addWidget(self.frame_16, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_17.addWidget(self.mid_stock_2)
        self.bottom_stock_2 = QtWidgets.QFrame(self.container_stock_2)
        self.bottom_stock_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_stock_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_stock_2.setObjectName("bottom_stock_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.bottom_stock_2)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_17 = QtWidgets.QFrame(self.bottom_stock_2)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.tableWidget_usuarios = QtWidgets.QTableWidget(self.frame_17)
        self.tableWidget_usuarios.setGeometry(QtCore.QRect(30, 40, 881, 501))
        self.tableWidget_usuarios.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_usuarios.setStyleSheet("QTableWidget{\n"
"font-size: 11pt;\n"
"margin-left: 0px;\n"
"margin-top:15px;\n"
"color: #000;\n"
"font-family: Roboto;\n"
"text-align:center;\n"
"}\n"
"QheaderView::item\n"
"    {\n"
"text-align:center;\n"
"\n"
"    }\n"
"QHeaderView::section {\n"
"    background-color: #394353;\n"
"    border-radius: 11px;\n"
"    color:#fff;\n"
"    font-size: 9pt;\n"
"    font-family:Roboto;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #394353;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"\n"
"    border-left: 1px solid #394353;\n"
"}")
        self.tableWidget_usuarios.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_usuarios.setShowGrid(False)
        self.tableWidget_usuarios.setObjectName("tableWidget_usuarios")
        self.tableWidget_usuarios.setColumnCount(5)
        self.tableWidget_usuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(4, item)
        self.tableWidget_usuarios.horizontalHeader().setVisible(False)
        self.tableWidget_usuarios.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_usuarios.horizontalHeader().setDefaultSectionSize(169)
        self.tableWidget_usuarios.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_usuarios.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_usuarios.verticalHeader().setVisible(False)
        self.tableWidget_usuarios.verticalHeader().setDefaultSectionSize(41)
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setGeometry(QtCore.QRect(20, 9, 861, 41))
        self.frame_18.setMinimumSize(QtCore.QSize(56, 41))
        self.frame_18.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius:15px;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_18 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18, 0, QtCore.Qt.AlignLeft)
        self.label_19 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"\n"
"")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19, 0, QtCore.Qt.AlignLeft)
        self.label_20 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_14.addWidget(self.label_20, 0, QtCore.Qt.AlignLeft)
        self.label_21 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21, 0, QtCore.Qt.AlignLeft)
        self.label_22 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22, 0, QtCore.Qt.AlignLeft)
        self.btn_actualizarUsuarios = QtWidgets.QPushButton(self.frame_17)
        self.btn_actualizarUsuarios.setGeometry(QtCore.QRect(880, 20, 31, 21))
        self.btn_actualizarUsuarios.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_actualizarUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizarUsuarios.setText("")
        self.btn_actualizarUsuarios.setIcon(icon8)
        self.btn_actualizarUsuarios.setIconSize(QtCore.QSize(33, 16))
        self.btn_actualizarUsuarios.setObjectName("btn_actualizarUsuarios")
        self.verticalLayout_21.addWidget(self.frame_17)
        self.verticalLayout_17.addWidget(self.bottom_stock_2)
        self.verticalLayout_16.addWidget(self.container_stock_2)
        self.stackedWidget_user.addWidget(self.page_usuarios2)
        self.page_movimientos_2 = QtWidgets.QWidget()
        self.page_movimientos_2.setObjectName("page_movimientos_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_movimientos_2)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.stackedWidget_user.addWidget(self.page_movimientos_2)
        self.verticalLayout_28.addWidget(self.stackedWidget_user)
        self.stackedWidget_main.addWidget(self.page_usuarios)
        self.page_areas = QtWidgets.QWidget()
        self.page_areas.setObjectName("page_areas")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_areas)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.page_areas)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tableWidget_areas = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget_areas.setGeometry(QtCore.QRect(20, 161, 961, 321))
        self.tableWidget_areas.setMaximumSize(QtCore.QSize(16777215, 422))
        self.tableWidget_areas.setStyleSheet("QTableWidget{\n"
"font-size: 11pt;\n"
"margin-left: 0px;\n"
"margin-top:15px;\n"
"color: #000;\n"
"font-family: Roboto;\n"
"text-align:center;\n"
"font-weight: bold;\n"
"}\n"
"QheaderView::item\n"
"    {\n"
"text-align:center;\n"
"font-weight: bold;\n"
"\n"
"    }\n"
"QHeaderView::section {\n"
"    background-color: #394353;\n"
"    border-radius: 11px;\n"
"    color:#fff;\n"
"    font-size: 9pt;\n"
"    font-family:Roboto;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border-top: 1px solid #394353;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"\n"
"    border-left: 1px solid #394353;\n"
"}")
        self.tableWidget_areas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_areas.setShowGrid(False)
        self.tableWidget_areas.setObjectName("tableWidget_areas")
        self.tableWidget_areas.setColumnCount(6)
        self.tableWidget_areas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_areas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_areas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_areas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_areas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_areas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_areas.setHorizontalHeaderItem(5, item)
        self.tableWidget_areas.horizontalHeader().setVisible(False)
        self.tableWidget_areas.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_areas.horizontalHeader().setDefaultSectionSize(147)
        self.tableWidget_areas.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_areas.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_areas.verticalHeader().setVisible(False)
        self.tableWidget_areas.verticalHeader().setDefaultSectionSize(32)
        self.frame_25 = QtWidgets.QFrame(self.frame_4)
        self.frame_25.setGeometry(QtCore.QRect(10, 110, 881, 41))
        self.frame_25.setMinimumSize(QtCore.QSize(56, 41))
        self.frame_25.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-radius:15px;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.label_35 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"\n"
"")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_5.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_5.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_5.addWidget(self.label_37)
        self.label_39 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_5.addWidget(self.label_39)
        self.label_38 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background: none;\n"
"color: #282830 ;\n"
"")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_5.addWidget(self.label_38)
        self.top_frame_stock_5 = QtWidgets.QFrame(self.frame_4)
        self.top_frame_stock_5.setGeometry(QtCore.QRect(0, 0, 1234, 80))
        self.top_frame_stock_5.setMinimumSize(QtCore.QSize(1234, 80))
        self.top_frame_stock_5.setMaximumSize(QtCore.QSize(15000, 70))
        self.top_frame_stock_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_stock_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_stock_5.setObjectName("top_frame_stock_5")
        self.frame_30 = QtWidgets.QFrame(self.top_frame_stock_5)
        self.frame_30.setGeometry(QtCore.QRect(0, 13, 891, 70))
        self.frame_30.setMinimumSize(QtCore.QSize(354, 70))
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_39.setSpacing(0)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame_30)
        self.groupBox_12.setMinimumSize(QtCore.QSize(675, 0))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_area_mod = QtWidgets.QLabel(self.groupBox_12)
        self.label_area_mod.setGeometry(QtCore.QRect(20, 10, 161, 52))
        self.label_area_mod.setMinimumSize(QtCore.QSize(94, 0))
        self.label_area_mod.setMaximumSize(QtCore.QSize(181, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_area_mod.setFont(font)
        self.label_area_mod.setStyleSheet("color: #282830 ;\n"
"")
        self.label_area_mod.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_area_mod.setObjectName("label_area_mod")
        self.btn_newPosicion = QtWidgets.QPushButton(self.groupBox_12)
        self.btn_newPosicion.setGeometry(QtCore.QRect(360, 26, 181, 26))
        self.btn_newPosicion.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_newPosicion.setFont(font)
        self.btn_newPosicion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_newPosicion.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color:#fff;\n"
"padding-right:15px;\n"
"border-radius: 5px;\n"
"text-align:right;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"\n"
"}")
        self.btn_newPosicion.setIcon(icon6)
        self.btn_newPosicion.setIconSize(QtCore.QSize(13, 13))
        self.btn_newPosicion.setObjectName("btn_newPosicion")
        self.btn_modificarArea = QtWidgets.QPushButton(self.groupBox_12)
        self.btn_modificarArea.setGeometry(QtCore.QRect(230, 26, 111, 26))
        self.btn_modificarArea.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_modificarArea.setFont(font)
        self.btn_modificarArea.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_modificarArea.setStyleSheet("QPushButton{\n"
"background-color: rgb(71, 71, 103);\n"
"color:#fff;\n"
"padding-right:15px;\n"
"border-radius: 5px;\n"
"text-align:right;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"\n"
"}")
        self.btn_modificarArea.setIconSize(QtCore.QSize(13, 13))
        self.btn_modificarArea.setObjectName("btn_modificarArea")
        self.btn_actualizarAreaInd = QtWidgets.QPushButton(self.groupBox_12)
        self.btn_actualizarAreaInd.setGeometry(QtCore.QRect(550, 30, 31, 21))
        self.btn_actualizarAreaInd.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_actualizarAreaInd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_actualizarAreaInd.setText("")
        self.btn_actualizarAreaInd.setIcon(icon8)
        self.btn_actualizarAreaInd.setIconSize(QtCore.QSize(33, 16))
        self.btn_actualizarAreaInd.setObjectName("btn_actualizarAreaInd")
        self.verticalLayout_39.addWidget(self.groupBox_12)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.stackedWidget_main.addWidget(self.page_areas)
        self.verticalLayout_2.addWidget(self.stackedWidget_main)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_3.setCurrentIndex(0)
        self.stackedWidget_main.setCurrentIndex(4)
        self.stackedWidget_user.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BullSoft"))
        self.label_7.setText(_translate("MainWindow", "Productos"))
        self.products_btn_stock.setText(_translate("MainWindow", "Stock"))
        self.products_btn_movimiento.setText(_translate("MainWindow", "Movimientos"))
        self.products_btn_lotes.setText(_translate("MainWindow", "Lotes"))
        self.label_9.setText(_translate("MainWindow", "Depósito"))
        self.label_12.setText(_translate("MainWindow", "Áreas"))
        self.label_10.setText(_translate("MainWindow", "Usuarios"))
        self.label_8.setText(_translate("MainWindow", "Stock"))
        self.product_new_btn.setText(_translate("MainWindow", "Nuevo Producto"))
        self.buscar_input.setPlaceholderText(_translate("MainWindow", "Buscar Productos por nombre o palabra clave"))
        item = self.tableWidget_stock_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_stock_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_stock_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_stock_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_stock_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_11.setText(_translate("MainWindow", "Código"))
        self.label_23.setText(_translate("MainWindow", "Descripción"))
        self.label_24.setText(_translate("MainWindow", "Marca"))
        self.label_25.setText(_translate("MainWindow", "Cantidad"))
        self.label_26.setText(_translate("MainWindow", "Primer Vencimiento"))
        self.label_27.setText(_translate("MainWindow", "Movimientos"))
        self.new_ingreso_btn.setText(_translate("MainWindow", "Ingreso"))
        self.new_egreso_btn.setText(_translate("MainWindow", "Egreso"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Buscar Movimientos por código, descripción,tipo o fecha"))
        item = self.tableWidget_movimientos_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_movimientos_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_movimientos_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_movimientos_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_movimientos_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_movimientos_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_28.setText(_translate("MainWindow", "Código"))
        self.label_29.setText(_translate("MainWindow", "Descripción"))
        self.label_30.setText(_translate("MainWindow", "Tipo de Movimiento"))
        self.label_32.setText(_translate("MainWindow", " Motivo"))
        self.label_31.setText(_translate("MainWindow", " Fecha "))
        self.label_33.setText(_translate("MainWindow", "Cantidad"))
        self.label_40.setText(_translate("MainWindow", "Lotes"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Buscar Lote por id del producto"))
        item = self.tableWidget_lotes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_lotes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_lotes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_lotes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_lotes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_41.setText(_translate("MainWindow", "Código del Producto"))
        self.label_42.setText(_translate("MainWindow", "Descripción"))
        self.label_43.setText(_translate("MainWindow", "Lote"))
        self.label_45.setText(_translate("MainWindow", " Fecha de Vencimiento"))
        self.label_46.setText(_translate("MainWindow", "Cantidad"))
        self.label_34.setText(_translate("MainWindow", "Áreas"))
        self.newArea_btn.setText(_translate("MainWindow", "Nueva Área"))
        self.newArea_btn_2.setText(_translate("MainWindow", "Eliminar Área"))
        self.label_17.setText(_translate("MainWindow", "Usuarios"))
        self.user_new_btn.setText(_translate("MainWindow", "Nuevo Usuario"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Buscar usuarios por DNI, nombre o apellido"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_18.setText(_translate("MainWindow", "Código"))
        self.label_19.setText(_translate("MainWindow", "Nombre"))
        self.label_20.setText(_translate("MainWindow", "Apellido"))
        self.label_21.setText(_translate("MainWindow", "Tipo"))
        self.label_22.setText(_translate("MainWindow", "Fecha de Nacimiento"))
        item = self.tableWidget_areas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_areas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_areas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_areas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_areas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_areas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_13.setText(_translate("MainWindow", "Código"))
        self.label_35.setText(_translate("MainWindow", "Descripción"))
        self.label_36.setText(_translate("MainWindow", "Marca"))
        self.label_37.setText(_translate("MainWindow", "Cantidad"))
        self.label_39.setText(_translate("MainWindow", "Ubicación"))
        self.label_38.setText(_translate("MainWindow", "Primer Vencimiento"))
        self.label_area_mod.setText(_translate("MainWindow", "Label"))
        self.btn_newPosicion.setText(_translate("MainWindow", "Posicion de Alojamiento"))
        self.btn_modificarArea.setText(_translate("MainWindow", "Modificar Área"))
from Interfaces.main import  img_oficiales_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
