# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nueva_estanteria.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 292)
        MainWindow.setMinimumSize(QtCore.QSize(387, 292))
        MainWindow.setSizeIncrement(QtCore.QSize(387, 292))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background: #f5f5f5")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.num_columnas = QtWidgets.QSpinBox(self.frame)
        self.num_columnas.setGeometry(QtCore.QRect(80, 110, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(9)
        self.num_columnas.setFont(font)
        self.num_columnas.setStyleSheet("border: 1px solid #b8b9bd;\n"
"background:#fff;")
        self.num_columnas.setObjectName("num_columnas")
        self.cbox_pasillo = QtWidgets.QComboBox(self.frame)
        self.cbox_pasillo.setGeometry(QtCore.QRect(210, 110, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(9)
        self.cbox_pasillo.setFont(font)
        self.cbox_pasillo.setStyleSheet("border: 1px solid #b8b9bd;\n"
"background:#fff;")
        self.cbox_pasillo.setObjectName("cbox_pasillo")
        self.num_niveles = QtWidgets.QSpinBox(self.frame)
        self.num_niveles.setGeometry(QtCore.QRect(80, 180, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(9)
        self.num_niveles.setFont(font)
        self.num_niveles.setStyleSheet("background:#fff;\n"
"border: 1px solid #b8b9bd")
        self.num_niveles.setObjectName("num_niveles")
        self.cbox_posicion = QtWidgets.QComboBox(self.frame)
        self.cbox_posicion.setGeometry(QtCore.QRect(210, 180, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(9)
        self.cbox_posicion.setFont(font)
        self.cbox_posicion.setStyleSheet("border: 1px solid #b8b9bd;\n"
"background:#fff;")
        self.cbox_posicion.setObjectName("cbox_posicion")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(210, 90, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #212325")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #212325")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 160, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #212325")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(210, 160, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #212325")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #212325;\n"
"margin-bottom: 5px")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.btn_nueva_estanteria = QtWidgets.QPushButton(self.frame)
        self.btn_nueva_estanteria.setGeometry(QtCore.QRect(130, 230, 121, 26))
        self.btn_nueva_estanteria.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Cairo SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_nueva_estanteria.setFont(font)
        self.btn_nueva_estanteria.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nueva_estanteria.setStyleSheet("QPushButton{\n"
"background-color: #055ffc;\n"
"color:#fff;\n"
"border-radius: 5px;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_nueva_estanteria.setIcon(icon)
        self.btn_nueva_estanteria.setIconSize(QtCore.QSize(13, 13))
        self.btn_nueva_estanteria.setObjectName("btn_nueva_estanteria")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Pasillo"))
        self.label_2.setText(_translate("MainWindow", "Columnas"))
        self.label_3.setText(_translate("MainWindow", "Niveles"))
        self.label_4.setText(_translate("MainWindow", "Posición"))
        self.label_5.setText(_translate("MainWindow", "Nueva estantería"))
        self.btn_nueva_estanteria.setText(_translate("MainWindow", "Crear estantería"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
