# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevo_producto_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 461)
        MainWindow.setToolTipDuration(0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background: #f5f5f5;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.crearprod_btn = QtWidgets.QPushButton(self.frame_2)
        self.crearprod_btn.setGeometry(QtCore.QRect(560, 400, 161, 27))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(9)
        self.crearprod_btn.setFont(font)
        self.crearprod_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crearprod_btn.setStyleSheet("QPushButton{\n"
"background-color: #055ffc;\n"
"color:#fff;\n"
"border-radius: 5px;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.crearprod_btn.setObjectName("crearprod_btn")
        self.subirFoto_btn = QtWidgets.QPushButton(self.frame_2)
        self.subirFoto_btn.setGeometry(QtCore.QRect(560, 360, 161, 27))
        self.subirFoto_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(9)
        self.subirFoto_btn.setFont(font)
        self.subirFoto_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.subirFoto_btn.setStyleSheet("QPushButton{\n"
"background-color: #055ffc;\n"
"color:#fff;\n"
"border-radius: 5px;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.subirFoto_btn.setObjectName("subirFoto_btn")
        self.codigo_input = QtWidgets.QLineEdit(self.frame_2)
        self.codigo_input.setGeometry(QtCore.QRect(60, 120, 170, 27))
        self.codigo_input.setMinimumSize(QtCore.QSize(0, 0))
        self.codigo_input.setMaximumSize(QtCore.QSize(16777215, 27))
        self.codigo_input.setStyleSheet("QLineEdit{\n"
"background: #fff;\n"
"border: 1px solid #b8b9bd;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #e9e9;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"}")
        self.codigo_input.setText("")
        self.codigo_input.setPlaceholderText("")
        self.codigo_input.setObjectName("codigo_input")
        self.label_peso = QtWidgets.QLabel(self.frame_2)
        self.label_peso.setGeometry(QtCore.QRect(280, 90, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_peso.setFont(font)
        self.label_peso.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_peso.setObjectName("label_peso")
        self.fragil_no = QtWidgets.QRadioButton(self.frame_2)
        self.fragil_no.setGeometry(QtCore.QRect(600, 120, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.fragil_no.setFont(font)
        self.fragil_no.setStyleSheet("font-family: Roboto;\n"
"font-size: 12px;")
        self.fragil_no.setIconSize(QtCore.QSize(30, 30))
        self.fragil_no.setObjectName("fragil_no")
        self.marca_input = QtWidgets.QLineEdit(self.frame_2)
        self.marca_input.setGeometry(QtCore.QRect(60, 310, 170, 27))
        self.marca_input.setMinimumSize(QtCore.QSize(0, 0))
        self.marca_input.setMaximumSize(QtCore.QSize(16777215, 27))
        self.marca_input.setStyleSheet("QLineEdit{\n"
"border: 1px solid #b8b9bd;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #e9e9;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"background: #fff;\n"
"\n"
"}\n"
"")
        self.marca_input.setPlaceholderText("")
        self.marca_input.setObjectName("marca_input")
        self.label_lote = QtWidgets.QLabel(self.frame_2)
        self.label_lote.setGeometry(QtCore.QRect(280, 220, 154, 27))
        self.label_lote.setMaximumSize(QtCore.QSize(154, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_lote.setFont(font)
        self.label_lote.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_lote.setObjectName("label_lote")
        self.label_ubicacion = QtWidgets.QLabel(self.frame_2)
        self.label_ubicacion.setGeometry(QtCore.QRect(60, 160, 91, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_ubicacion.setFont(font)
        self.label_ubicacion.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_ubicacion.setObjectName("label_ubicacion")
        self.posicion_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.posicion_comboBox.setGeometry(QtCore.QRect(550, 190, 170, 27))
        self.posicion_comboBox.setStyleSheet("border: 1px solid #b8b9bd;border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: rgb(0, 0, 0);\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"background: #fff;\n"
"")
        self.posicion_comboBox.setObjectName("posicion_comboBox")
        self.descripcion_input = QtWidgets.QTextEdit(self.frame_2)
        self.descripcion_input.setGeometry(QtCore.QRect(60, 190, 170, 81))
        self.descripcion_input.setStyleSheet("border: 1px solid #b8b9bd;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #e9e9;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"background: #fff;\n"
"")
        self.descripcion_input.setObjectName("descripcion_input")
        self.peso_num = QtWidgets.QSpinBox(self.frame_2)
        self.peso_num.setGeometry(QtCore.QRect(280, 120, 170, 27))
        self.peso_num.setStyleSheet("border: 1px solid #b8b9bd;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: rgb(0, 0, 0);\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"background: #fff;\n"
"")
        self.peso_num.setMinimum(0)
        self.peso_num.setMaximum(9999)
        self.peso_num.setObjectName("peso_num")
        self.lote_input = QtWidgets.QLineEdit(self.frame_2)
        self.lote_input.setGeometry(QtCore.QRect(280, 250, 170, 27))
        self.lote_input.setMinimumSize(QtCore.QSize(0, 0))
        self.lote_input.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lote_input.setStyleSheet("QLineEdit{\n"
"border: 1px solid #b8b9bd;border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #e9e9;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"background: #fff;\n"
"\n"
"}\n"
"")
        self.lote_input.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lote_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lote_input.setPlaceholderText("")
        self.lote_input.setObjectName("lote_input")
        self.label_area = QtWidgets.QLabel(self.frame_2)
        self.label_area.setGeometry(QtCore.QRect(550, 160, 90, 27))
        self.label_area.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_area.setFont(font)
        self.label_area.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_area.setObjectName("label_area")
        self.venc_date = QtWidgets.QDateEdit(self.frame_2)
        self.venc_date.setGeometry(QtCore.QRect(550, 310, 170, 27))
        self.venc_date.setStyleSheet("background: #fff;\n"
"\n"
"border: 1px solid #b8b9bd;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #000;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"")
        self.venc_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.venc_date.setObjectName("venc_date")
        self.label_cantidad = QtWidgets.QLabel(self.frame_2)
        self.label_cantidad.setGeometry(QtCore.QRect(280, 280, 158, 27))
        self.label_cantidad.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_cantidad.setFont(font)
        self.label_cantidad.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_cantidad.setObjectName("label_cantidad")
        self.label_area_2 = QtWidgets.QLabel(self.frame_2)
        self.label_area_2.setGeometry(QtCore.QRect(550, 220, 169, 27))
        self.label_area_2.setMaximumSize(QtCore.QSize(179, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_area_2.setFont(font)
        self.label_area_2.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_area_2.setObjectName("label_area_2")
        self.area_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.area_comboBox.setGeometry(QtCore.QRect(550, 250, 170, 27))
        self.area_comboBox.setStyleSheet("border: 1px solid #b8b9bd;padding: 4 5px;\n"
"color: rgb(0, 0, 0);\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"background: #fff;\n"
"")
        self.area_comboBox.setObjectName("area_comboBox")
        self.label_marca = QtWidgets.QLabel(self.frame_2)
        self.label_marca.setGeometry(QtCore.QRect(60, 280, 100, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_marca.setFont(font)
        self.label_marca.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_marca.setObjectName("label_marca")
        self.fragil_si = QtWidgets.QRadioButton(self.frame_2)
        self.fragil_si.setGeometry(QtCore.QRect(560, 120, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.fragil_si.setFont(font)
        self.fragil_si.setStyleSheet("font-family: Roboto;\n"
"font-size: 12px;\n"
"background:")
        self.fragil_si.setIconSize(QtCore.QSize(30, 30))
        self.fragil_si.setObjectName("fragil_si")
        self.label_codigo = QtWidgets.QLabel(self.frame_2)
        self.label_codigo.setGeometry(QtCore.QRect(60, 90, 101, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_codigo.setFont(font)
        self.label_codigo.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_codigo.setObjectName("label_codigo")
        self.cantidad_num = QtWidgets.QSpinBox(self.frame_2)
        self.cantidad_num.setGeometry(QtCore.QRect(280, 310, 170, 27))
        self.cantidad_num.setStyleSheet("border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: rgb(0, 0, 0);\n"
"font-family:Roboto;\n"
"border: 1px solid #b8b9bd;font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"background: #fff;\n"
"")
        self.cantidad_num.setMinimum(0)
        self.cantidad_num.setMaximum(9999)
        self.cantidad_num.setObjectName("cantidad_num")
        self.label_vencimiento = QtWidgets.QLabel(self.frame_2)
        self.label_vencimiento.setGeometry(QtCore.QRect(550, 280, 161, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_vencimiento.setFont(font)
        self.label_vencimiento.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_vencimiento.setObjectName("label_vencimiento")
        self.label_fragil = QtWidgets.QLabel(self.frame_2)
        self.label_fragil.setGeometry(QtCore.QRect(550, 90, 90, 27))
        self.label_fragil.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_fragil.setFont(font)
        self.label_fragil.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_fragil.setObjectName("label_fragil")
        self.label_lote_2 = QtWidgets.QLabel(self.frame_2)
        self.label_lote_2.setGeometry(QtCore.QRect(280, 160, 154, 27))
        self.label_lote_2.setMaximumSize(QtCore.QSize(154, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_lote_2.setFont(font)
        self.label_lote_2.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_lote_2.setObjectName("label_lote_2")
        self.num_volumen = QtWidgets.QSpinBox(self.frame_2)
        self.num_volumen.setGeometry(QtCore.QRect(280, 190, 170, 27))
        self.num_volumen.setStyleSheet("border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: rgb(0, 0, 0);\n"
"font-family:Roboto;\n"
"border: 1px solid #b8b9bd;font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"background: #fff;\n"
"")
        self.num_volumen.setMinimum(0)
        self.num_volumen.setMaximum(9999)
        self.num_volumen.setObjectName("num_volumen")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(0, 20, 861, 61))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #212325;\n"
"margin-bottom: 5px")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_marca_2 = QtWidgets.QLabel(self.frame_2)
        self.label_marca_2.setGeometry(QtCore.QRect(60, 340, 100, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_marca_2.setFont(font)
        self.label_marca_2.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_marca_2.setObjectName("label_marca_2")
        self.num_precio = QtWidgets.QSpinBox(self.frame_2)
        self.num_precio.setGeometry(QtCore.QRect(60, 370, 170, 27))
        self.num_precio.setStyleSheet("border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: rgb(0, 0, 0);\n"
"font-family:Roboto;\n"
"border: 1px solid #b8b9bd;font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"background: #fff;\n"
"")
        self.num_precio.setMinimum(0)
        self.num_precio.setMaximum(9999)
        self.num_precio.setObjectName("num_precio")
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nuevo Producto"))
        self.crearprod_btn.setText(_translate("MainWindow", "Crear producto"))
        self.subirFoto_btn.setText(_translate("MainWindow", "Subir Imagen"))
        self.label_peso.setText(_translate("MainWindow", "Peso (g)"))
        self.fragil_no.setText(_translate("MainWindow", "NO"))
        self.label_lote.setText(_translate("MainWindow", "Lote"))
        self.label_ubicacion.setText(_translate("MainWindow", "Descripción"))
        self.label_area.setText(_translate("MainWindow", "Área"))
        self.label_cantidad.setText(_translate("MainWindow", "Cantidad"))
        self.label_area_2.setText(_translate("MainWindow", "Posición de Alojamiento"))
        self.label_marca.setText(_translate("MainWindow", "Marca"))
        self.fragil_si.setText(_translate("MainWindow", "SI"))
        self.label_codigo.setText(_translate("MainWindow", "Código EAN"))
        self.label_vencimiento.setText(_translate("MainWindow", "Fecha De Vencimiento"))
        self.label_fragil.setText(_translate("MainWindow", "Frágil"))
        self.label_lote_2.setText(_translate("MainWindow", "Volumen"))
        self.label_5.setText(_translate("MainWindow", "Nuevo Producto"))
        self.label_marca_2.setText(_translate("MainWindow", "Precio"))
from Interfaces.main import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
